twilio:
  account_sid: AC6277d4bb7daa1a3f784d7eae63cc4ece
  auth_token: be2525e9968419fdddbd7eda165db2cd
  trial_number: +15706832019

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/healthMate
    password: ala
    username: ala
  application:
    name: healthMate
  mail:
    host: localhost
    port: 1025
    username: ala
    password: ala
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 500
        timeout: 3000
        writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 500MB

application:
  security:
    jwt:
      secret-key: yhwdxGYjqMr3qRBFFxF3l7si5Q9PfetGI1TD0t4sl06ksSdvyhgLss8YL066tJsZ
      expiration : 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  servlet:
    context-path: /api/v1
